### ISSUE TITLE
the problem about meta-learning

### ISSUE THREAD

**Issue by changyungting** [seongmin-kye/meta-SR#5]
Thank you very much for developing such a great project and publishing it to the public. When I was reading your code, I have some questions and would like to ask you. Because I am new to meta-learning, in my current understanding, meta-learning should have two optimizers, one for specific tasks and the other for the whole task, but I did not find a global optimizer (for the whole task) in your code. Would you please answer me? Looking forward to your reply, thank you!!

**Comment by seongmin-kye** [comment]
Hi. Meta learning can be divided into two categories, optimization based and metric based method. In optimization based method such as MAML, as you said, there are inner loop and outer loop. But, in metric based method such as Prototypical Networks, no additional gradient step is needed.
Thanks.
